[package]
name = "dylib_math_game"
version = "0.1.0"
edition = "2024"
lint.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
# singularity_sap = { path = "../../singularity_sap" }
singularity_sttk = { path = "../../singularity_sttk" }
singularity_ui = { path = "../../singularity_ui" }
