[workspace]
members = [
    "singularity_ui",
    # "singularity_sap",

    "singularity_common",
    "singularity_common/singularity_macros",

    "singularity_sporg",
    "singularity_sde",
    "singularity_sttk",
    "singularity_standard_tabs",
    # "singularity_standard_tabs/*", # TODO: make the asterisk work
    "singularity_standard_tabs/dylib_math_game",
    "singularity_sar",
    "singularity_wl_compositor",

    # "dynamic_plugin_sandbox/server",
    # "dynamic_plugin_sandbox/client",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
uuid = { version = "^1.10.0", features = ["v4", "serde"] }
paste = { version = "1" }
libloading = { version = "^0.8" }
libc = { version = "^0.2" }

tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
log = { version = "^0.4" }

image = { version = "^0.25" }

# [[members]]
# singularity_ui = { features = ["iced_backend"] }
