[workspace]
members = [
    "singularity_common",
    "singularity_manager",
    "singularity_standard_tabs",
]
resolver = "2"

[workspace.dependencies]
winit = "0.30"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libloading = "0.8"
