[workspace]
members = [
    "singularity_common",
    "singularity_manager",
    "singularity_standard_tabs",
]


[workspace.dependencies]
ratatui = { version = "0.28", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libloading = "0.8"
