[workspace]
members = [
    "singularity_common",
    "singularity_common/sonamu_ui",

    "singularity_sporg",
    "singularity_sde",
    "singularity_sttk",
    "singularity_standard_tabs",
    "singularity_sar",
    "singularity_wl_compositor",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
uuid = { version = "^1.23.3", features = ["v4", "serde"] }
paste = { version = "1" }
libloading = { version = "^0.9" }
libc = { version = "^0.2" }

tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
log = { version = "^0.4" }

image = { version = "^0.25" }

sonamu_ui = { path = "./singularity_common/sonamu_ui" }
sonamu_sync = { path = "./singularity_common/sonamu_sync" }

[workspace.lints.clippy]
# all = "warn"
pedantic = { level = "warn", priority = -1 }
# nursery = "warn" # these are for experimental lints
cargo = { level = "warn", priority = -1 }

# all the pedantic stuff I'm not going to listen to:

# something with common things to put in a Crate like liscence and stuff
# TODO: enable; I'll do these if I ever put this on crates.io
cargo_common_metadata = "allow"
# I think this technically bloats the system but might be inevitable?
# I also just don't have wifi rn so I can't do anything about it rn...
multiple_crate_versions = "allow"

# Doc suggestions that are too pedantic, especially since it's just me developing rn
doc_markdown = "allow"
too_long_first_doc_paragraph = "allow" # more like too_long_lint_name (bam roasted)
missing_panics_doc = "allow"
missing_errors_doc = "allow"

# opinionated stuff
match_same_arms = "allow"
match_wildcard_for_single_variants = "allow"
semicolon_if_nothing_returned = "allow"
similar_names = "allow"
unsafe_derive_deserialize = "allow"
cast_possible_wrap = "allow"
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
items_after_statements = "allow"
struct_excessive_bools = "allow"
struct_field_name = "allow"
must_use_candidate = "allow"                 # having must_use everywhere is getting kinda ugly

[workspace.lints.rust]
unused_qualifications = "warn"
