[workspace]
members = ["singularity_common", "singularity_manager", "singularity_subapps/*"]


[workspace.dependencies]
ratatui = "0.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
