[package]
name = "singularity_wl_compositor"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
singularity_common = { path = "../singularity_common" }
sonamu_ui = { workspace = true }
singularity_sporg = { path = "../singularity_sporg" }
singularity_sar = { path = "../singularity_sar" }
singularity_sttk = { path = "../singularity_sttk" }

tracing-subscriber = { workspace = true }
log = { workspace = true }

image = { workspace = true }

# Smithay doesn't post the newest version to crates.io
# smithay = { version = "^0.7.0", features = ["wayland_frontend"] }
smithay = { git = "https://github.com/Smithay/smithay", branch = "master", features = [
    "wayland_frontend",
    # "wayland-protocols",
] }
wayland-protocols = { version = "0.32.12", features = [
    "unstable",
    "staging",
    "server",
] }

[build-dependencies]
regex = "1.12"
