[package]
name = "singularity_sar"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
# singularity_macros = { path = "../singularity_common/singularity_macros" }
singularity_common = { workspace = true }
sonamu_ui = { workspace = true }
sonamu_sync = { workspace = true }

slotmap = { workspace = true }

calloop = { workspace = true }

pollster.workspace = true

wgpu.workspace = true

# TODO: put this behind a feature
smithay.workspace = true
wayland-protocols.workspace = true

image.workspace = true
