[package]
name = "singularity_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
# egui = "^0.28"
# eframe = "^0.28"
# winit = "^0.29"
# iced = "0.12"
wayland-client = "^0.31"

[features]
default = ["wayland_backend"]
iced_backend = []
egui_backend = []
wayland_backend = []

# [[bin]]
# name = "demo"
# path = "src/demo.rs"
