[package]
name = "singularity_sde"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
singularity_standard_tabs = { path = "../singularity_standard_tabs" }
singularity_sar = { path = "../singularity_sar" }
singularity_sttk = { path = "../singularity_sttk" }
singularity_wl_compositor = { path = "../singularity_wl_compositor" }

tracing-subscriber = { workspace = true }
