[package]
name = "singularity_sde"
version = "0.1.0"
edition = "2024"

[dependencies]
singularity_common = { path = "../singularity_common" }
singularity_macros = { path = "../singularity_common/singularity_macros" }
singularity_standard_tabs = { path = "../singularity_standard_tabs" }
singularity_ui = { path = "../singularity_ui" }
# singularity_sap = { path = "../singularity_sap", features = [
#     "standard_packets",
# ] }
singularity_sporg = { path = "../singularity_sporg" }
singularity_sar = { path = "../singularity_sar" }
singularity_sttk = { path = "../singularity_sttk" }
singularity_wl_compositor = { path = "../singularity_wl_compositor" }

serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
