[package]
name = "singularity_common"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
libloading = { workspace = true }
