[package]
name = "singularity_common"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
singularity_macros = { path = "./singularity_macros" }
sonamu_ui = { workspace = true }
sonamu_sync = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

uuid = { workspace = true }
# just replace id tree with this?
slotmap = { workspace = true }

paste = { workspace = true }

calloop = { workspace = true }
