[package]
name = "singularity_standard_tabs"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
singularity_common = { path = "../singularity_common" }
sonamu_ui = { workspace = true }
singularity_sar = { path = "../singularity_sar" }
singularity_sttk = { path = "../singularity_sttk" }

log = { workspace = true }

arboard = { version = "^3.6.1", features = ["wayland-data-control"] }

image = { workspace = true }

# things needed for editor
ropey = { version = "1.6.1" } # TODO:  checkout version 2 whiich is in beta rn
